### ISSUE TITLE
Add "section" selector drop down on new, update and print pages

### ISSUE THREAD

**Issue by mannishmajhi** [mannishmajhi/Mechi_Multiple_Campus#2]
## Keep it just below semester
![image](https://github.com/mannishmajhi/Mechi_Multiple_Campus/assets/158675603/be3a4aaf-a717-4d4d-aa47-eec0feb7a6cf)

**Comment by bhawesh-mishra** [comment]
Added "section" selector drop down on new, update and print pages.
